spring:
  application:
    name: restfulapi

  datasource:
    url: jdbc:mysql://localhost:3306/moneytransferdb?createDatabaseIfNotExist=true
    username: root
    password: Root123$

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
