spring:
  application:
    name: moneytransfer

  datasource:
    url: jdbc:mysql://localhost:3306/moneytransferdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root123$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC
    # (REMOVED) serialization.WRITE_DATES_AS_TIMESTAMPS: false  <-- don't include this

security:
  jwt:
    issuer: "mts-app"
    # Set from environment in real life:
    #export JWT_SECRET=$(openssl rand -base64 32)
    secret: "${JWT_SECRET:VGhpcy1zLWp1c3QtYS1kZXYtc2VjcmV0LTMxMmJpdHMhIQ==}"
    expiry-minutes: 30


server:
  port: 8080