spring:
  application:
    name: moneytransfer

  datasource:
    url: "jdbc:mysql://localhost:3306/moneytransferdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
    username: "root"
    password: "Root123$"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: always
      # If data.sql is at src/main/resources/data.sql, you can remove this line entirely
      # data-locations: classpath:data.sql

  jackson:
    time-zone: UTC

logging:
  level:
    root: INFO
    com.mts: DEBUG
    org.hibernate.SQL: DEBUG

security:
  jwt:
    issuer: "mts-app"
    secret: "${JWT_SECRET:VGhpcy1zLWp1c3QtYS1kZXYtc2VjcmV0LTMxMmJpdHMhIQ==}"
    expiry-minutes: 30

server:
  port: 8080